!function(l,h,g){var e=function(a,c){var b=this;this.el=a;this.options={};Object.keys(k).forEach(function(a){b.options[a]=k[a]});Object.keys(c).forEach(function(a){b.options[a]=c[a]});this.isInput="input"===this.el.tagName.toLowerCase();this.attr=this.options.attr;this.showCursor=this.isInput?!1:this.options.showCursor;this.elContent=this.attr?this.el.getAttribute(this.attr):this.el.textContent;this.contentType=this.options.contentType;this.typeSpeed=this.options.typeSpeed;this.startDelay=this.options.startDelay;
this.backSpeed=this.options.backSpeed;this.backDelay=this.options.backDelay;this.fadeOut=this.options.fadeOut;this.fadeOutClass=this.options.fadeOutClass;this.fadeOutDelay=this.options.fadeOutDelay;this.stringsElement=g&&this.options.stringsElement instanceof g?this.options.stringsElement[0]:this.options.stringsElement;this.strings=this.options.strings;this.stopNum=this.arrayPos=this.strPos=0;this.loop=this.options.loop;this.loopCount=this.options.loopCount;this.curLoop=0;this.stop=!1;this.cursorChar=
this.options.cursorChar;this.shuffle=this.options.shuffle;this.sequence=[];this.build()};e.prototype={constructor:e,init:function(){var a=this;a.timeout=setTimeout(function(){for(var c=0;c<a.strings.length;++c)a.sequence[c]=c;a.shuffle&&(a.sequence=a.shuffleArray(a.sequence));a.typewrite(a.strings[a.sequence[a.arrayPos]],a.strPos)},a.startDelay)},build:function(){var a=this;!0===this.showCursor&&(this.cursor=h.createElement("span"),this.cursor.className="typed-cursor",this.cursor.innerHTML=this.cursorChar,
this.el.parentNode&&this.el.parentNode.insertBefore(this.cursor,this.el.nextSibling));this.stringsElement&&(this.strings=[],this.stringsElement.style.display="none",Array.prototype.slice.apply(this.stringsElement.children).forEach(function(c){a.strings.push(c.innerHTML)}));this.init()},typewrite:function(a,c){if(!0!==this.stop){this.fadeOut&&this.el.classList.contains(this.fadeOutClass)&&(this.el.classList.remove(this.fadeOutClass),this.cursor.classList.remove(this.fadeOutClass));var b=this;b.timeout=
setTimeout(function(){var d=0,f=a.substr(c);if("^"===f.charAt(0)){var e=1;/^\^\d+/.test(f)&&(f=/\d+/.exec(f)[0],e+=f.length,d=parseInt(f));a=a.substring(0,c)+a.substring(c+e)}if("html"===b.contentType&&(f=a.substr(c).charAt(0),"<"===f||"&"===f)){for(var g=e="",g="<"===f?">":";";a.substr(c+1).charAt(0)!==g&&!(e+=a.substr(c).charAt(0),c++,c+1>a.length););c++;e+=g}b.timeout=setTimeout(function(){if(c===a.length){b.options.onStringTyped(b.arrayPos);if(b.arrayPos===b.strings.length-1&&(b.options.callback(),
b.curLoop++,!1===b.loop||b.curLoop===b.loopCount))return;b.timeout=setTimeout(function(){b.backspace(a,c)},b.backDelay)}else{0===c&&b.options.preStringTyped(b.arrayPos);var d=a.substr(0,c+1);b.attr?b.el.setAttribute(b.attr,d):b.isInput?b.el.value=d:"html"===b.contentType?b.el.innerHTML=d:b.el.textContent=d;c++;b.typewrite(a,c)}},d)},Math.round(70*Math.random())+this.typeSpeed)}},backspace:function(a,c){var b=this;!0!==this.stop&&(this.fadeOut?this.initFadeOut():b.timeout=setTimeout(function(){if("html"===
b.contentType&&">"===a.substr(c).charAt(0)){for(var d="";"<"!==a.substr(c-1).charAt(0)&&!(d-=a.substr(c).charAt(0),c--,0>c););c--}d=a.substr(0,c);b.replaceText(d);c>b.stopNum?(c--,b.backspace(a,c)):c<=b.stopNum&&(b.arrayPos++,b.arrayPos===b.strings.length?(b.arrayPos=0,b.shuffle&&(b.sequence=b.shuffleArray(b.sequence)),b.init()):b.typewrite(b.strings[b.sequence[b.arrayPos]],c))},Math.round(70*Math.random())+this.backSpeed))},initFadeOut:function(){self=this;this.el.className+=" "+this.fadeOutClass;
this.cursor.className+=" "+this.fadeOutClass;return setTimeout(function(){self.arrayPos++;self.replaceText("");self.typewrite(self.strings[self.sequence[self.arrayPos]],0)},self.fadeOutDelay)},replaceText:function(a){this.attr?this.el.setAttribute(this.attr,a):this.isInput?this.el.value=a:"html"===this.contentType?this.el.innerHTML=a:this.el.textContent=a},shuffleArray:function(a){var c=a.length;if(c)for(;--c;){var b=Math.floor(Math.random()*(c+1));var d=a[b];a[b]=a[c];a[c]=d}return a},reset:function(){clearInterval(this.timeout);
this.el.getAttribute("id");this.el.textContent="";"undefined"!==typeof this.cursor&&"undefined"!==typeof this.cursor.parentNode&&this.cursor.parentNode.removeChild(this.cursor);this.curLoop=this.arrayPos=this.strPos=0;this.options.resetCallback()}};e["new"]=function(a,c){Array.prototype.slice.apply(h.querySelectorAll(a)).forEach(function(a){var b=a._typed,f="object"==typeof c&&c;b&&b.reset();a._typed=b=new e(a,f);if("string"==typeof c)b[c]()})};g&&(g.fn.typed=function(a){return this.each(function(){var c=
g(this),b=c.data("typed"),d="object"==typeof a&&a;b&&b.reset();c.data("typed",b=new e(this,d));if("string"==typeof a)b[a]()})});l.Typed=e;var k={strings:["These are the default values...","You know what you should do?","Use your own!","Have a great day!"],stringsElement:null,typeSpeed:0,startDelay:0,backSpeed:0,shuffle:!1,backDelay:500,fadeOut:!1,fadeOutClass:"typed-fade-out",fadeOutDelay:500,loop:!1,loopCount:!1,showCursor:!0,cursorChar:"|",attr:null,contentType:"html",callback:function(){},preStringTyped:function(){},
onStringTyped:function(){},resetCallback:function(){}}}(window,document,window.jQuery);
